### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugargame#14]
On Ubuntu 22.04, the test activity and the IQ activity open a blank window.

**Comment by chimosky** [comment]
Issue no longer exists.

**Comment by quozl** [comment]
It still exists, and I've reproduced just now.  Ubuntu 22.04, pygame 2.1.2, SDL 2.0.20, Python 3.10.12.

First, a pygame window appears;

![Screenshot_ujj_2024-04-01_11:38:05](https://github.com/sugarlabs/sugargame/assets/2936481/e6fef6fc-2a00-4778-9262-32784f218fa1)

Then, the activity toolbar renders over the top of it;

![Screenshot_ujj_2024-04-01_11:38:34](https://github.com/sugarlabs/sugargame/assets/2936481/c1252839-8be0-4aaf-b915-28cea2982b71)

**Comment by Ark74** [comment]
The latest trisquel-sugar 11.0.1 iso (22.04 based) still trigger the issue too.
One of the reasons it was removed from the default install.

https://cdbuilds.trisquel.org/aramo/11.0.1/

```
libsdl2-2.0-0:amd64 2.26.5+dfsg-1+11.0trisquel0
python3-pygame 2.1.2+dfsg-3+11.0trisquel0
python3 3.10.6-1~22.04
```

**Comment by quozl** [comment]
Thanks @Ark74.  I've dug into the problem.  Cause was in SDL and Pygame applied a fix.

Here's results of testing the Sugargame test activity by Pygame release, each one using `pip install pygame=RELEASE`, and then confirming the test activity shows the requested release.

| Release | Result |
| ----- | ----- |
| 1.9.6 | does not install |
| 2.0.0 | does not install |
| 2.0.1 | does not install |
| 2.0.2 | does not install |
| 2.0.3 | reproduced |
| 2.1.0 | reproduced |
| 2.1.1 | reproduced and segmentation fault |
| 2.1.2 | reproduced |
| 2.1.3 | reproduced, plus bouncing ball, plus x server crash |
| 2.2.0.dev2 | does not reproduce |
| 2.2.0 | does not reproduce |
| 2.5.2 | does not reproduce |

* between 2.1.3 and 2.2.0.dev2 was c767838e ("display: Use SDL_strtol to get SDL_WINDOWID") src_c/display.c and was very likely the fix,
* https://github.com/pygame/pygame/issues/1574 was the issue that triggered the change; SDL dropped support for `SDL_WINDOWID` as used by Sugargame, many other applications broke, and Pygame put it back into Pygame instead.

We've seen it before on Physics.  See https://github.com/sugarlabs/physics/issues/50 for the full list of affected activities, but the issue was closed once Physics seemed to work.

**Comment by Ark74** [comment]
@quozl interesting, I've tested porting this patch:
* https://github.com/pygame/pygame/pull/2981/files

to pygame and it seems to be working fine.
![iq-working](https://github.com/sugarlabs/sugargame/assets/7444518/f25c09d7-c95f-430b-afe0-3e1342b542bc)

This version should fix it via updates:
```
python3-pygame 2.1.2+dfsg-3+11.0trisquel1
```

**Comment by quozl** [comment]
Well done.  Yep, that's the patch.  The later patch that I mentioned above is cleanup.  For Ubuntu 22.04 my guess is we're stuck with it, and should workaround using "pip install pygame=2.5.2".  For Ubuntu 24.04 it already has Pygame 2.5.2.  I'll now stop failing pull request reviews on the basis of the problem. :grin:

**Comment by chimosky** [comment]
> Well done. Yep, that's the patch. The later patch that I mentioned above is cleanup. For Ubuntu 22.04 my guess is we're stuck with it, and should workaround using "pip install pygame=2.5.2". For Ubuntu 24.04 it already has Pygame 2.5.2. I'll now stop failing pull request reviews on the basis of the problem. 😁

Yes, Ubuntu 22.04 having a version <2.2 is the problem.
